apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-8-benchmark
  labels:
    app: camunda-8-benchmark
spec:
  selector:
    matchLabels:
      app: camunda-8-benchmark
  replicas: 1
  template:
    metadata:
      labels:
        app: camunda-8-benchmark
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: camunda-8-benchmark
          image: nevergonagiveyouup/camunda-8-benchmark-rework:latest
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTIONS
              value: >-
                -Dbenchmark.startPiPerSecond=5
                -Dbenchmark.startRateAdjustmentStrategy=none
                -Dbenchmark.taskCompletionDelay=10
                -Dbenchmark.bpmnProcessId=benchmark
                -Dbenchmark.jobType=benchmark-task
                -Dbenchmark.payloadPath=classpath:bpmn/typical_payload.json
                -Dbenchmark.autoDeployProcess=true                
                -Dbenchmark.maxBackpressurePercentage=10.0
                -Dbenchmark.startPiReduceFactor=1
                -Dbenchmark.startPiIncreaseFactor=1
                -Dzeebe.client.broker.gateway-address=camunda-platform-zeebe-gateway.camunda-platform.svc.cluster.local:26500
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: camunda-8-benchmark

spec:
  selector:
    app: camunda-8-benchmark
  ports:
    - port: 8088
      targetPort: 8088