name: Build and Deploy to Docker
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker
        run: docker build . -t ${{ secrets.DOCKER_PASSWORD }}/camunda-8-benchmark-rework:latest

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_PASSWORD }}/camunda-8-benchmark-rework:latest